# Generated by Django 6.1.1 on 2026-09-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_categoria_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='referencia_transferencia',
            new_name='referencia_pago',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20),
        ),
    ]
