# Generated by Django 6.1.1 on 2026-09-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_rename_referencia_transferencia_pedido_referencia_pago_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='referencia_pago',
            new_name='referencia_transferencia',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pagado_en',
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('mercadopago', 'MercadoPago'), ('binance', 'Binance Pay / USDT'), ('zelle', 'Zelle')], default='transferencia', max_length=20),
        ),
    ]
